project:
  type: website
  
    
website:
  title: "Dynamical Systems with R"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: dsystems.qmd
        text: Dynamical Systems   
      - href: chaos.qmd
        text: Chaos
      - href: fractal.qmd
        text: Fractals   

format:
  html:
    theme: darkly
    toc: true